-- Mainframe Banking V2 schema (lab)
-- Synthetic educational model. Not a real bank.

CREATE TABLE BANK_CIF (
  CIF_NO        CHAR(10) NOT NULL PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(30),
  ADDRESS       VARCHAR(50),
  KYC_STAT      CHAR(1),
  REL_MGR       CHAR(8)
);

CREATE TABLE BANK_CUSTOMER (
  ACCOUNT_NO    CHAR(6) NOT NULL PRIMARY KEY,
  CIF_NO        CHAR(10),
  CUSTOMER_NAME VARCHAR(30),
  STATUS        CHAR(1),
  BRANCH_NO     CHAR(6),
  REGION        CHAR(4),
  BALANCE       DECIMAL(15,2),
  HOLD_AMT      DECIMAL(15,2),
  OD_LIMIT      DECIMAL(15,2),
  LAST_POST_TS  TIMESTAMP,
  OPEN_DTE      DATE,
  CCY           CHAR(3) DEFAULT 'USD'
);

CREATE TABLE BANK_JOURNAL (
  TRACE_ID      VARCHAR(26) NOT NULL PRIMARY KEY,
  ACCOUNT_NO    CHAR(6),
  LOC_ID        CHAR(8),
  CHANNEL       CHAR(8),
  DR_CR         CHAR(1),
  AMOUNT        DECIMAL(15,2),
  CYCLE_DTE     DATE,
  POSTED_IND    CHAR(1),
  REVERSAL_OF   VARCHAR(26),
  TERM_ID       CHAR(8),
  TELLER_ID     CHAR(8),
  CREATE_TS     TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  POST_TS       TIMESTAMP,
  NARR          VARCHAR(40)
);
CREATE INDEX IX_JRN_ACC ON BANK_JOURNAL(ACCOUNT_NO);
CREATE INDEX IX_JRN_CYC ON BANK_JOURNAL(CYCLE_DTE, LOC_ID);
CREATE INDEX IX_JRN_TRACE ON BANK_JOURNAL(TRACE_ID);

CREATE TABLE BANK_LOCATION_FILE_CTL (
  LOC_ID         CHAR(8) NOT NULL,
  CYCLE_DTE      DATE NOT NULL,
  GEN_NO         INTEGER,
  ARRIVED_IND    CHAR(1),
  VALIDATED_IND  CHAR(1),
  HASH_DR        DECIMAL(17,2),
  HASH_CR        DECIMAL(17,2),
  REC_COUNT      INTEGER,
  DSNAME         VARCHAR(44),
  PRIMARY KEY (LOC_ID, CYCLE_DTE)
);

CREATE TABLE BANK_LOCATION_XTR (
  TRACE_ID    VARCHAR(26) NOT NULL PRIMARY KEY,
  LOC_ID      CHAR(8),
  CYCLE_DTE   DATE,
  ACCOUNT_NO  CHAR(6),
  DR_CR       CHAR(1),
  AMOUNT      DECIMAL(15,2),
  CHANNEL     CHAR(8)
);

CREATE TABLE BANK_RECON_XCPT (
  XCPT_ID     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CYCLE_DTE   DATE,
  LOC_ID      CHAR(8),
  TRACE_ID    VARCHAR(26),
  ACCOUNT_NO  CHAR(6),
  REASON      VARCHAR(16),
  AMOUNT      DECIMAL(15,2),
  STATUS      CHAR(1)
);

CREATE TABLE BANK_CYCLE_CTL (
  CYCLE_DTE        DATE NOT NULL PRIMARY KEY,
  STATUS           CHAR(8),
  ONLINE_INHIBIT   CHAR(1),
  VALIDATED_IND    CHAR(1),
  RECON_CLOSED     CHAR(1),
  LOCK_OWNER       CHAR(8)
);

CREATE TABLE BANK_RESTART (
  CYCLE_DTE   DATE NOT NULL PRIMARY KEY,
  LAST_TRACE  VARCHAR(26),
  CHUNK_NO    INTEGER,
  MODE        CHAR(8)
);

CREATE TABLE BANK_HOLD (
  HOLD_ID     CHAR(12) NOT NULL PRIMARY KEY,
  ACCOUNT_NO  CHAR(6),
  AMOUNT      DECIMAL(15,2),
  REASON      VARCHAR(20),
  EXP_DTE     DATE,
  STATUS      CHAR(1)
);

CREATE TABLE BANK_ATM_ADVICE (
  TRACE_ID    VARCHAR(26) NOT NULL PRIMARY KEY,
  PAN_HASH    CHAR(16),
  TERM_ID     CHAR(8),
  AMOUNT      DECIMAL(15,2),
  DISP_IND    CHAR(1),
  REV_OF      VARCHAR(26),
  SWITCH_TS   TIMESTAMP,
  CASSETTE    CHAR(4)
);

CREATE TABLE BANK_GL_FEED (
  FEED_ID     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CYCLE_DTE   DATE,
  GL_ACCT     CHAR(10),
  CCY         CHAR(3),
  DR_CR       CHAR(1),
  AMOUNT      DECIMAL(15,2),
  SRC_LOC     CHAR(8),
  NARR        VARCHAR(40)
);

CREATE TABLE BANK_TELLER (
  TELLER_ID     CHAR(8) NOT NULL PRIMARY KEY,
  BRANCH_NO     CHAR(6),
  DRAWER_CASH   DECIMAL(15,2),
  SIGNED_ON     CHAR(1),
  OVERRIDE_LVL  INTEGER
);

CREATE TABLE BANK_BRANCH_CASH (
  BRANCH_NO    CHAR(6) NOT NULL PRIMARY KEY,
  VAULT_CASH   DECIMAL(15,2),
  TELLER_TOT   DECIMAL(15,2),
  IN_TRANSIT   DECIMAL(15,2),
  AS_OF        DATE
);

CREATE TABLE BANK_INT_ACCRUAL (
  ACCOUNT_NO  CHAR(6),
  CYCLE_DTE   DATE,
  ACCRUAL     DECIMAL(15,2),
  RATE_BP     INTEGER
);


-- V2 expansion tables (lab)

ALTER TABLE BANK_CIF ADD COLUMN ADDR1 VARCHAR(40);
ALTER TABLE BANK_CIF ADD COLUMN STATE CHAR(2);
ALTER TABLE BANK_CIF ADD COLUMN TIN CHAR(9);
ALTER TABLE BANK_CIF ADD COLUMN TIN_STAT CHAR(1);
ALTER TABLE BANK_CIF ADD COLUMN OFAC_STAT CHAR(1);
ALTER TABLE BANK_CIF ADD COLUMN DUAL_PEND CHAR(1);

ALTER TABLE BANK_CUSTOMER ADD COLUMN PROD CHAR(4);
ALTER TABLE BANK_CUSTOMER ADD COLUMN AVAIL_AMT DECIMAL(15,2);
ALTER TABLE BANK_CUSTOMER ADD COLUMN NSF_COUNT INTEGER DEFAULT 0;
ALTER TABLE BANK_CUSTOMER ADD COLUMN LAST_CUST_DTE DATE;

ALTER TABLE BANK_JOURNAL ADD COLUMN MEMO_IND CHAR(1) DEFAULT 'N';
ALTER TABLE BANK_JOURNAL ADD COLUMN CHECK_NO DECIMAL(10,0);
ALTER TABLE BANK_JOURNAL ADD COLUMN GL_ACCT CHAR(10);

ALTER TABLE BANK_HOLD ADD COLUMN HOLD_TYPE CHAR(8);
ALTER TABLE BANK_CYCLE_CTL ADD COLUMN GL_PROVED CHAR(1);

CREATE TABLE BANK_STOP (
  STOP_ID     CHAR(12) NOT NULL PRIMARY KEY,
  ACCOUNT_NO  CHAR(6) NOT NULL,
  KIND        CHAR(1),
  CHECK_NO    DECIMAL(10,0),
  CHECK_THRU  DECIMAL(10,0),
  AMOUNT      DECIMAL(15,2),
  AMT_OPT     CHAR(1),
  PAYEE       VARCHAR(30),
  EXPIRE_DTE  DATE,
  STATUS      CHAR(1),
  FEE_AMT     DECIMAL(9,2),
  TELLER_ID   CHAR(8),
  CREATE_TS   TIMESTAMP
);
CREATE INDEX IX_STOP_ACC ON BANK_STOP(ACCOUNT_NO, CHECK_NO);

CREATE TABLE BANK_ACH_BATCH (
  BATCH_NO      INTEGER NOT NULL,
  CYCLE_DTE     DATE NOT NULL,
  SEC_CODE      CHAR(3),
  CO_ID         CHAR(10),
  SERV_CLASS    INTEGER,
  ENTRY_CNT     INTEGER,
  HASH_TOTAL    DECIMAL(12,0),
  TOT_DR        DECIMAL(15,2),
  TOT_CR        DECIMAL(15,2),
  WINDOW        CHAR(8),
  STATUS        CHAR(1),
  PRIMARY KEY (CYCLE_DTE, BATCH_NO)
);

CREATE TABLE BANK_ACH_ENTRY (
  ACH_TRACE     CHAR(15) NOT NULL PRIMARY KEY,
  BATCH_NO      INTEGER,
  CYCLE_DTE     DATE,
  TX_CODE       INTEGER,
  RDFID         CHAR(9),
  DDA           CHAR(17),
  ACCOUNT_NO    CHAR(6),
  AMOUNT        DECIMAL(15,2),
  INDIV_NAME    VARCHAR(22),
  SEC_CODE      CHAR(3),
  RETURN_CODE   CHAR(3),
  ORIG_TRACE    CHAR(15),
  STATUS        CHAR(1)
);
CREATE INDEX IX_ACH_ACC ON BANK_ACH_ENTRY(ACCOUNT_NO, CYCLE_DTE);

CREATE TABLE BANK_CARD_AUTH (
  AUTH_ID     CHAR(12) NOT NULL PRIMARY KEY,
  PAN_HASH    CHAR(16),
  ACCOUNT_NO  CHAR(6),
  AUTH_AMT    DECIMAL(15,2),
  CAPTURE_AMT DECIMAL(15,2),
  MCC         CHAR(4),
  NETWORK     CHAR(4),
  POS_MODE    CHAR(2),
  STATUS      CHAR(1),
  HOLD_ID     CHAR(12),
  AUTH_TS     TIMESTAMP
);

CREATE TABLE BANK_CARD_PRES (
  ARN         CHAR(23) NOT NULL PRIMARY KEY,
  AUTH_ID     CHAR(12),
  TRACE_ID    VARCHAR(26),
  AMOUNT      DECIMAL(15,2),
  SURCHARGE   DECIMAL(9,2),
  CB_REASON   CHAR(4),
  CB_CYCLE    INTEGER
);

CREATE TABLE BANK_PP_ISSUED (
  ACCOUNT_NO  CHAR(6) NOT NULL,
  SERIAL      DECIMAL(10,0) NOT NULL,
  AMOUNT      DECIMAL(15,2),
  PAYEE       VARCHAR(40),
  ISSUE_DTE   DATE,
  STATUS      CHAR(1),
  PRIMARY KEY (ACCOUNT_NO, SERIAL)
);

CREATE TABLE BANK_PP_XCPT (
  XCPT_ID     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ACCOUNT_NO  CHAR(6),
  SERIAL      DECIMAL(10,0),
  ISS_AMT     DECIMAL(15,2),
  PRE_AMT     DECIMAL(15,2),
  REASON      CHAR(12),
  DECISION    CHAR(1),
  DECIDER     CHAR(8),
  CYCLE_DTE   DATE
);

CREATE TABLE BANK_LOAN (
  NOTE_NO       CHAR(10) NOT NULL PRIMARY KEY,
  ACCOUNT_NO    CHAR(6),
  PRIN_BAL      DECIMAL(15,2),
  INT_ACCRUED   DECIMAL(15,2),
  ESCROW_BAL    DECIMAL(15,2),
  LATE_FEE_DUE  DECIMAL(9,2),
  RATE_BP       INTEGER,
  DUE_DTE       DATE,
  STATUS        CHAR(1)
);

CREATE TABLE BANK_ZBA (
  CHILD_ACC   CHAR(6) NOT NULL PRIMARY KEY,
  PARENT_ACC  CHAR(6) NOT NULL,
  TARGET_BAL  DECIMAL(15,2),
  MIN_SWEEP   DECIMAL(15,2),
  VEHICLE     CHAR(8),
  STATUS      CHAR(1)
);

CREATE TABLE BANK_OFAC_HIT (
  HIT_ID      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CIF_NO      CHAR(10),
  RAW_NAME    VARCHAR(80),
  SCORE       INTEGER,
  SDN_ID      CHAR(12),
  LIST_NAME   CHAR(8),
  STATUS      CHAR(1),
  CHANNEL     CHAR(8),
  HIT_TS      TIMESTAMP
);

CREATE TABLE BANK_CTR (
  CIF_NO      CHAR(10) NOT NULL,
  BUS_DTE     DATE NOT NULL,
  CASH_IN     DECIMAL(15,2),
  CASH_OUT    DECIMAL(15,2),
  OCCUPATION  VARCHAR(30),
  SRC_FUNDS   VARCHAR(30),
  BENEFICIARY VARCHAR(30),
  FILED_IND   CHAR(1),
  EXEMPT_IND  CHAR(1),
  TELLER_ID   CHAR(8),
  BRANCH_NO   CHAR(6),
  PRIMARY KEY (CIF_NO, BUS_DTE)
);

CREATE TABLE BANK_CALENDAR (
  CAL_DTE       DATE NOT NULL PRIMARY KEY,
  DOW           INTEGER,
  HOLIDAY_IND   CHAR(1),
  HOLIDAY_NAME  VARCHAR(24),
  FED_OPEN      CHAR(1),
  NEXT_BUS      DATE,
  PREV_BUS      DATE,
  SAME_DAY_CUT  CHAR(8),
  WIRE_CUT      CHAR(8)
);

CREATE TABLE BANK_AVAIL (
  TRACE_ID    VARCHAR(26) NOT NULL PRIMARY KEY,
  ACCOUNT_NO  CHAR(6),
  AMOUNT      DECIMAL(15,2),
  DEP_DTE     DATE,
  AVAIL_DTE   DATE,
  HOLD_DAYS   INTEGER,
  AVL_CLASS   CHAR(8),
  REASON      CHAR(16),
  STATUS      CHAR(1)
);

CREATE TABLE BANK_TAX_1099 (
  CIF_NO      CHAR(10) NOT NULL,
  TAX_YEAR    INTEGER NOT NULL,
  INT_YTD     DECIMAL(15,2),
  WH_YTD      DECIMAL(15,2),
  TIN         CHAR(9),
  TIN_STAT    CHAR(1),
  FILED_IND   CHAR(1),
  PRIMARY KEY (CIF_NO, TAX_YEAR)
);

CREATE TABLE BANK_UCP (
  ACCOUNT_NO      CHAR(6) NOT NULL PRIMARY KEY,
  CIF_NO          CHAR(10),
  STATE           CHAR(2),
  DORM_YEARS      INTEGER,
  LAST_CUST_DTE   DATE,
  NOTICE_DTE      DATE,
  STATUS          CHAR(1),
  REPORT_YEAR     INTEGER
);

CREATE TABLE BANK_ESCROW_DUE (
  LOAN_NO     CHAR(10) NOT NULL,
  ESC_TYPE    CHAR(8) NOT NULL,
  DUE_DTE     DATE NOT NULL,
  PAYEE       VARCHAR(40),
  AMOUNT      DECIMAL(15,2),
  STATUS      CHAR(1),
  PRIMARY KEY (LOAN_NO, ESC_TYPE, DUE_DTE)
);

CREATE TABLE BANK_FEE_SCHED (
  PROD        CHAR(4) NOT NULL,
  FEE_CODE    CHAR(8) NOT NULL,
  AMOUNT      DECIMAL(9,2),
  WAIVE_BAL   DECIMAL(15,2),
  PRIMARY KEY (PROD, FEE_CODE)
);

CREATE TABLE BANK_SUSPENSE (
  SUSP_ID     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CYCLE_DTE   DATE,
  TRACE_ID    VARCHAR(26),
  ACCOUNT_NO  CHAR(6),
  AMOUNT      DECIMAL(15,2),
  REASON      VARCHAR(16),
  FORCE_IND   CHAR(1),
  DUAL_USER   CHAR(8),
  STATUS      CHAR(1)
);

CREATE TABLE BANK_GL_MAP (
  CHANNEL     CHAR(8) NOT NULL,
  DR_CR       CHAR(1) NOT NULL,
  PROD        CHAR(4) NOT NULL,
  GL_ACCT     CHAR(10) NOT NULL,
  PRIMARY KEY (CHANNEL, DR_CR, PROD)
);

INSERT INTO BANK_GL_MAP (CHANNEL, DR_CR, PROD, GL_ACCT) VALUES
  ('TELLER  ','D','DDA ','1010001000'),
  ('TELLER  ','C','DDA ','2010001000'),
  ('ATM     ','D','DDA ','1010002000'),
  ('ATM     ','C','DDA ','2010002000'),
  ('ACH     ','D','DDA ','1010003000'),
  ('ACH     ','C','DDA ','2010003000'),
  ('WIRE    ','D','DDA ','1010004000'),
  ('WIRE    ','C','DDA ','2010004000'),
  ('BATCH   ','D','DDA ','1010005000'),
  ('BATCH   ','C','DDA ','2010005000'),
  ('CORR    ','D','DDA ','1010006000'),
  ('CORR    ','C','DDA ','2010006000');
